
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BoardofPardons.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Form
{

    public Form()
    {

        this.IncarceratedStep1 = new HashSet<IncarceratedStep1>();

        this.IncarceratedStep2 = new HashSet<IncarceratedStep2>();

        this.IncarceratedStep3 = new HashSet<IncarceratedStep3>();

        this.IncarceratedStep4 = new HashSet<IncarceratedStep4>();

        this.IncarceratedStep5 = new HashSet<IncarceratedStep5>();

        this.IncarceratedStep6 = new HashSet<IncarceratedStep6>();

        this.IncarceratedStep7 = new HashSet<IncarceratedStep7>();

        this.NonIncarceratedStep2 = new HashSet<NonIncarceratedStep2>();

        this.NonIncarceratedStep3 = new HashSet<NonIncarceratedStep3>();

        this.NonIncarceratedStep4 = new HashSet<NonIncarceratedStep4>();

        this.NonIncarceratedStep5 = new HashSet<NonIncarceratedStep5>();

        this.NonIncarceratedStep6 = new HashSet<NonIncarceratedStep6>();

        this.NonIncarceratedStep7 = new HashSet<NonIncarceratedStep7>();

        this.NonIncarceratedStep1 = new HashSet<NonIncarceratedStep1>();

        this.Reviews = new HashSet<Review>();

    }


    public int id { get; set; }

    public int UserId { get; set; }

    public int Type { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }

    public int Status { get; set; }



    public virtual webpages_Membership webpages_Membership { get; set; }

    public virtual ICollection<IncarceratedStep1> IncarceratedStep1 { get; set; }

    public virtual ICollection<IncarceratedStep2> IncarceratedStep2 { get; set; }

    public virtual ICollection<IncarceratedStep3> IncarceratedStep3 { get; set; }

    public virtual ICollection<IncarceratedStep4> IncarceratedStep4 { get; set; }

    public virtual ICollection<IncarceratedStep5> IncarceratedStep5 { get; set; }

    public virtual ICollection<IncarceratedStep6> IncarceratedStep6 { get; set; }

    public virtual ICollection<IncarceratedStep7> IncarceratedStep7 { get; set; }

    public virtual ICollection<NonIncarceratedStep2> NonIncarceratedStep2 { get; set; }

    public virtual ICollection<NonIncarceratedStep3> NonIncarceratedStep3 { get; set; }

    public virtual ICollection<NonIncarceratedStep4> NonIncarceratedStep4 { get; set; }

    public virtual ICollection<NonIncarceratedStep5> NonIncarceratedStep5 { get; set; }

    public virtual ICollection<NonIncarceratedStep6> NonIncarceratedStep6 { get; set; }

    public virtual ICollection<NonIncarceratedStep7> NonIncarceratedStep7 { get; set; }

    public virtual ICollection<NonIncarceratedStep1> NonIncarceratedStep1 { get; set; }

    public virtual ICollection<Review> Reviews { get; set; }

}

}
