
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BoardofPardons.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class NonIncarceratedStep5
{

    public int Id { get; set; }

    public int FormId { get; set; }

    public bool OtherCharges { get; set; }

    public string DateIncident1 { get; set; }

    public string OtherSF1 { get; set; }

    public string OffensesAdditional1 { get; set; }

    public string DispositionAdditional1 { get; set; }

    public string DateIncident2 { get; set; }

    public string OtherSF2 { get; set; }

    public string OffensesAdditional2 { get; set; }

    public string DispositionAdditional2 { get; set; }

    public string DateIncident3 { get; set; }

    public string OtherSF3 { get; set; }

    public string OffensesAdditional3 { get; set; }

    public string DispositionAdditional3 { get; set; }

    public string DateIncident4 { get; set; }

    public string OtherSF4 { get; set; }

    public string OffensesAdditional4 { get; set; }

    public string DispositionAdditional4 { get; set; }

    public string DateIncident5 { get; set; }

    public string OtherSF5 { get; set; }

    public string OffensesAdditional5 { get; set; }

    public string DispositionAdditional5 { get; set; }

    public bool JuvineleCharges { get; set; }

    public string DateJuvenile1 { get; set; }

    public string JuvenileCountyState1 { get; set; }

    public string OffensesJuvenile1 { get; set; }

    public Nullable<bool> JuvenileDelinquent1 { get; set; }

    public string DispositionJuvenile1 { get; set; }

    public string DateJuvenile2 { get; set; }

    public string JuvenileCountyState2 { get; set; }

    public string OffensesJuvenile2 { get; set; }

    public Nullable<bool> JuvenileDelinquent2 { get; set; }

    public string DispositionJuvenile2 { get; set; }

    public bool NonTraffic { get; set; }

    public string DatenNonTraffic1 { get; set; }

    public string CountyNonTraffic1 { get; set; }

    public string OffensesNonTraffic1 { get; set; }

    public string DispositionNonTraffic1 { get; set; }

    public string DatenNonTraffic2 { get; set; }

    public string CountyNonTraffic2 { get; set; }

    public string OffensesNonTraffic2 { get; set; }

    public string DispositionNonTraffic2 { get; set; }

    public string DatenNonTraffic3 { get; set; }

    public string CountyNonTraffic3 { get; set; }

    public string OffensesNonTraffic3 { get; set; }

    public string DispositionNonTraffic3 { get; set; }

    public string DatenNonTraffic4 { get; set; }

    public string CountyNonTraffic4 { get; set; }

    public string OffensesNonTraffic4 { get; set; }

    public string DispositionNonTraffic4 { get; set; }

    public bool Traffic { get; set; }

    public string DateTraffic1 { get; set; }

    public string CountyTraffic1 { get; set; }

    public string OffensesTraffic1 { get; set; }

    public string DispositionTraffic1 { get; set; }

    public string DateTraffic2 { get; set; }

    public string CountyTraffic2 { get; set; }

    public string OffensesTraffic2 { get; set; }

    public string DispositionTraffic2 { get; set; }

    public string DateTraffic3 { get; set; }

    public string CountyTraffic3 { get; set; }

    public string OffensesTraffic3 { get; set; }

    public string DispositionTraffic3 { get; set; }

    public string DateTraffic4 { get; set; }

    public string CountyTraffic4 { get; set; }

    public string OffensesTraffic4 { get; set; }

    public string DispositionTraffic4 { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }



    public virtual Form Form { get; set; }

}

}
