
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BoardofPardons.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class NonIncarceratedStep6
{

    public int Id { get; set; }

    public int FormId { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }

    public bool AquireCitizenship { get; set; }

    public bool Adoption { get; set; }

    public bool CivicActivities { get; set; }

    public bool Education { get; set; }

    public bool Employment { get; set; }

    public bool GunPermit { get; set; }

    public bool Housing { get; set; }

    public bool Licensures { get; set; }

    public bool MilitaryService { get; set; }

    public bool TravelingOutside { get; set; }

    public bool Other { get; set; }

    public string Specifications { get; set; }

    public string Reason { get; set; }

    public string Rehabilitations { get; set; }

    public string Contributions { get; set; }



    public virtual Form Form { get; set; }

}

}
