
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BoardofPardons.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class NonIncarceratedStep1
{

    public int Id { get; set; }

    public int FormId { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }

    public string ClemencyRequested { get; set; }

    public bool HaveFiled { get; set; }

    public string Previous { get; set; }

    public Nullable<bool> OtherState { get; set; }

    public string WhereFiled { get; set; }

    public Nullable<bool> GrantedOtherState { get; set; }

    public Nullable<System.DateTime> DateOtherStateGranted { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string Suffix { get; set; }

    public System.DateTime BirthDate { get; set; }

    public string BirthPlace { get; set; }

    public string Gender { get; set; }

    public string SSN { get; set; }

    public string Race { get; set; }

    public string ApplicantAddress { get; set; }

    public string Appartment { get; set; }

    public string ApplicantCity { get; set; }

    public string ApplicantState { get; set; }

    public string ApplicantZip { get; set; }

    public string ApplicantPhone { get; set; }

    public string CellPhone { get; set; }

    public string Email { get; set; }

    public string Aliases { get; set; }

    public string WhoRep { get; set; }

    public string Title { get; set; }

    public string Address { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Phone { get; set; }



    public virtual Form Form { get; set; }

}

}
