
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BoardofPardons.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Review
{

    public int Id { get; set; }

    public int FormId { get; set; }

    public int ReviewerId { get; set; }

    public int Status { get; set; }

    public System.DateTime ReviewedAt { get; set; }

    public string Comment { get; set; }



    public virtual Form Form { get; set; }

    public virtual webpages_Membership webpages_Membership { get; set; }

}

}
