
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BoardofPardons.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public User()
    {

        this.webpages_Roles = new HashSet<webpages_Roles>();

    }


    public int Id { get; set; }

    public string UserName { get; set; }

    public string Suffix { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Gender { get; set; }

    public System.DateTime BirthDate { get; set; }

    public string SSNumber { get; set; }

    public string Address { get; set; }

    public string Apartment { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Homephone { get; set; }

    public string CellPhone { get; set; }

    public string Email { get; set; }

    public string PlaceOfBirth { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }



    public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }

}

}
